# Site settings
title: Perl Advent Calendar 2024 CFP
tag_text: Perl Advent Calendar 2024 CFP
description: The Call For Participation for the 2024 Perl Advent Calendar
url: "https://cfp.perladvent.org"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
